<a href="https://colab.research.google.com/github/madhav7034/Assessment/blob/main/Numpy%26Pandas_Madhav.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#1

import numpy as np

arr = np.arange(10, 50)
reshaped = arr.reshape(4, 10)
last_col = reshaped[:, -1]

print("1. Original Array:\n", arr)
print('\n')
print("Reshaped (4x10):\n", reshaped)
print('\n')
print("Last Column:\n", last_col)


1. Original Array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Reshaped (4x10):
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


Last Column:
 [19 29 39 49]


In [3]:
#2


mat1 = np.full((3, 3), 5)
mat2 = np.arange(1, 10).reshape(3, 3)

added = mat1 + mat2
multiplied = mat1 * mat2
transposed = multiplied.T

print("\n2. Matrix 1 (All 5s):\n", mat1)
print("Matrix 2 (1 to 9):\n", mat2)
print("Added:\n", added)
print("Element-wise Multiplied:\n", multiplied)
print("Transpose of Result:\n", transposed)



2. Matrix 1 (All 5s):
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Matrix 2 (1 to 9):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Added:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Element-wise Multiplied:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose of Result:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [5]:
#3

rand_arr = np.random.randint(10, 101, 15)
replaced_arr = np.where(rand_arr > 50, -1, rand_arr)
count_replaced = np.sum(rand_arr > 50)

print("\n3. Original Random Array:\n", rand_arr)
print("After Replacing >50 with -1:\n", replaced_arr)
print("Count of Values Replaced:", count_replaced)



3. Original Random Array:
 [69 27 56 90 93 84 45 81 85 66 11 18 44 55 31]
After Replacing >50 with -1:
 [-1 27 -1 -1 -1 -1 45 -1 -1 -1 11 18 44 -1 31]
Count of Values Replaced: 9


In [7]:
#4

array_3 = np.random.random((5,4))
row_sums = np.sum(array_3, 1)
max_sum_ind = np.argmax(row_sums)

def normalize(arr):
  row_min = np.min(arr, axis=-1, keepdims=True)
  row_max = np.max(arr, axis=-1, keepdims=True)
  norm = (arr - row_min) / (row_max - row_min)
  return np.round(norm, 2)



normalized = normalize(array_3)

print(f'5X4 row :\n{array_3}\n')
print(f'Row with maximum sum:\n{array_3[max_sum_ind]}\n')
print(f'Normalized array:\n{normalized}')

5X4 row :
[[0.23732137 0.20739688 0.71298892 0.54569111]
 [0.03694633 0.82658346 0.4589308  0.74009495]
 [0.22236133 0.09177563 0.83632816 0.49104978]
 [0.46329764 0.98912804 0.59238053 0.6592677 ]
 [0.83422764 0.68186599 0.94008318 0.22675548]]

Row with maximum sum:
[0.46329764 0.98912804 0.59238053 0.6592677 ]

Normalized array:
[[0.06 0.   1.   0.67]
 [0.   1.   0.53 0.89]
 [0.18 0.   1.   0.54]
 [0.   1.   0.25 0.37]
 [0.85 0.64 1.   0.  ]]


In [9]:
#5

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique = np.unique(arr)

counts = np.bincount(arr)
duplicates = np.where(counts > 1)[0]

print("Unique Elements:\n", unique)
print("Duplicates:\n", duplicates)


Unique Elements:
 [1 3 5 7 9]
Duplicates:
 [1 3 5]


In [11]:
#6

arr = np.arange(1, 37).reshape(6, 6)
submatrix = arr[1:5, 1:5]
even_numbers = submatrix[submatrix % 2 == 0]

print("\n6. Original 6x6 Array:\n", arr)
print("Middle 4x4 Submatrix:\n", submatrix)
print("Even Numbers in Submatrix:\n", even_numbers)



6. Original 6x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Middle 4x4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even Numbers in Submatrix:
 [ 8 10 14 16 20 22 26 28]


In [12]:
#7

arr = np.arange(12).reshape(3, 4)
reshaped = arr.reshape(2, 6)
flattened = reshaped.flatten()
reshaped_again = flattened.reshape(4, 3)

print("\n7. Original 3x4 Array:\n", arr)
print("Reshaped to 2x6:\n", reshaped)
print("Flattened to 1D:\n", flattened)
print("Reshaped to 4x3:\n", reshaped_again)



7. Original 3x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened to 1D:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
#8



a = np.array([[1, 2], [3, 4]])
row_added = np.vstack([a, [[5, 6]]])
column_added = np.hstack([row_added, [[7], [8], [9]]])

print(f'array a:\n{a}\n')
print(f'array after appending row:\n{row_added}\n')
print(f'array after appending row and column:\n{column_added}')

array a:
[[1 2]
 [3 4]]

array after appending row:
[[1 2]
 [3 4]
 [5 6]]

array after appending row and column:
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [19]:
#9


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.concatenate([a, b, c])
e = d.reshape((3, 3))
f = np.diag(e)

print(f'Joined array d:\n{d}\n')
print(f'Reshaped array:\n{e}\n')
print(f'Extracted elements:\n{f}')

Joined array d:
[1 2 3 4 5 6 7 8 9]

Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Extracted elements:
[1 5 9]


In [20]:
#10

arr = np.arange(1, 21)
filtered = arr[(arr % 3 == 0) | (arr % 5 == 0)]
count = filtered.size

print("\n10. Original Array:\n", arr)
print("Values Divisible by 3 or 5:\n", filtered)
print("Count:", count)


10. Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Values Divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]
Count: 9


Pandas

In [22]:


import pandas as pd
import numpy as np

import seaborn as sns

In [23]:
#1

data=sns.load_dataset("titanic")

In [24]:
data.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [25]:
#2

data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [26]:
#3

percentage=data.groupby("sex")["survived"].mean()*100
percentage.round(2)

sex
female    74.20
male      18.89
Name: survived, dtype: float64

In [27]:
#4


age=data['age']
avr=age.mean()
med=age.median()
std_age=age.std()
print(avr)
print(med)
print(std_age)

29.69911764705882
28.0
14.526497332334044


In [28]:
#5

pclass=data['pclass']
pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [29]:
#6

survived_female = data[(data['sex'] == 'female') & (data['age'] < 18) & (data['survived'] == 1)]
display(survived_female)

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

In [31]:
#7

age.fillna(med,inplace=True)
age


0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [32]:
#8


conditions = [data['age'] < 18, (data['age'] >= 18) & (data['age'] < 60), data['age']>60]
values = ['Child','Adult', 'Senior']
data['age_group'] = np.select(conditions, values, default='Unknown')
data.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male  28.0      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False    C    Cherbourg   yes  False     Adult  
2  woman       False  NaN  Southampton   yes   True     Adult  
3  woman       False    C  Southampton   yes  False     Adult  
4    man        True  NaN  Southampton    no   True     Adult  
5    man        True  NaN   Queenstown    no   True     Adult  
6    man        True    E  Southampton    no   True     Adult  
7  child       False  NaN  Southampton    no  False     Child  
8  woman       False  NaN  Southampton   yes  False     Adult  
9  child       False  NaN    Cherbourg   yes  False     Child

In [33]:
#9

data = data.sort_values("fare",ascending=False)
data.head()

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior

In [34]:
#10

data.groupby(['pclass','sex'])["fare"].mean()

pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64

In [35]:
#11


data.rename(columns={ 'sex' :'gender','fare' : 'ticket_fare'},inplace=True)
data.head()


survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  \
679         1       1    male  36.0      0      1     512.3292        C   
258         1       1  female  35.0      0      0     512.3292        C   
737         1       1    male  35.0      0      0     512.3292        C   
88          1       1  female  23.0      3      2     263.0000        S   
438         0       1    male  64.0      1      4     263.0000        S   

     class    who  adult_male deck  embark_town alive  alone age_group  
679  First    man        True    B    Cherbourg   yes  False     Adult  
258  First  woman       False  NaN    Cherbourg   yes   True     Adult  
737  First    man        True    B    Cherbourg   yes   True     Adult  
88   First  woman       False    C  Southampton   yes  False     Adult  
438  First    man        True    C  Southampton    no  False    Senior

In [36]:
#12

survived_by_class = data.groupby(['class', 'survived']).size()
display(survived_by_class)

/tmp/ipython-input-461438671.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survived_by_class = data.groupby(['class', 'survived']).size()


class   survived
First   0            80
        1           136
Second  0            97
        1            87
Third   0           372
        1           119
dtype: int64

In [37]:
#13

average_age =data.groupby(["class","gender"])["age"].mean()
display(average_age)

/tmp/ipython-input-590633109.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_age =data.groupby(["class","gender"])["age"].mean()


class   gender
First   female    33.978723
        male      38.995246
Second  female    28.703947
        male      30.512315
Third   female    23.572917
        male      26.911873
Name: age, dtype: float64